name: 🚀 新需求 Feature Request
description: 提交一个你对PaddleDetection的新需求。 Submit a request for a new Paddle feature.
labels: [feature request]

body:
- type: markdown
  attributes:
    value: >
      #### 请统一前往[Roadmap Of PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/issues/7892)提出新特性或者新功能的需求。
      #### Please Go to [Roadmap Of PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/issues/7892) to submit a request for a new feature.

- type: markdown
  attributes:
    value: >
      感谢你的贡献 🎉！Thanks for your contribution 🎉!
